[2024-06-19 13:30:16,463] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Crear_tabla manual__2024-06-19T13:30:15.061796+00:00 [queued]>
[2024-06-19 13:30:16,477] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Crear_tabla manual__2024-06-19T13:30:15.061796+00:00 [queued]>
[2024-06-19 13:30:16,477] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:30:16,478] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-19 13:30:16,478] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:30:16,498] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): Crear_tabla> on 2024-06-19 13:30:15.061796+00:00
[2024-06-19 13:30:16,503] {standard_task_runner.py:52} INFO - Started process 503 to run task
[2024-06-19 13:30:16,506] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Crear_tabla', 'manual__2024-06-19T13:30:15.061796+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_posgres.py', '--cfg-path', '/var/tmp/tmp9_rc4unt', '--error-file', '/var/tmp/tmphi4zfmlm']
[2024-06-19 13:30:16,508] {standard_task_runner.py:80} INFO - Job 34: Subtask Crear_tabla
[2024-06-19 13:30:16,586] {task_command.py:371} INFO - Running <TaskInstance: tecnica_postgres.Crear_tabla manual__2024-06-19T13:30:15.061796+00:00 [running]> on host 284150aff6b6
[2024-06-19 13:30:16,687] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tecnica_postgres
AIRFLOW_CTX_TASK_ID=Crear_tabla
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T13:30:15.061796+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-19T13:30:15.061796+00:00
[2024-06-19 13:30:16,702] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-19 13:30:16,716] {dbapi.py:231} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS tecnica_ml (
            id VARCHAR(255),
            title VARCHAR(255),
            price VARCHAR(255),
            thumbnail VARCHAR(255),
            created_date VARCHAR(50),
            PRIMARY KEY (id, created_date)
        );
        , parameters: None
[2024-06-19 13:30:16,723] {postgres.py:94} INFO - NOTICE:  relation "tecnica_ml" already exists, skipping

[2024-06-19 13:30:16,928] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tecnica_postgres, task_id=Crear_tabla, execution_date=20240619T133015, start_date=20240619T133016, end_date=20240619T133016
[2024-06-19 13:30:16,960] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-06-19 13:30:17,008] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
